name: Test Go TDD example

on:
  workflow_dispatch
  #  push:
  #  branches:
  #    - 'dev'
  #  paths:
  #    - 'Exemplos/E02/goTdd/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: './Exemplos/E02/goTdd'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Get dependencies
        run: |
          go get -v -t -d ./...    
      - name: Test
        run: go test -v --cover .
